name:                gh-alerts-subscriptions-haskell
version:             0.1.0.0
github:              "githubuser/gh-alerts-subscriptions-haskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/gh-alerts-subscriptions-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- servant #http
- hspec #tests
- mtl #monad transformers
- async #Async
- time #DateTime manager
- text #Overriding strings
- uuid #UUID
- exceptions
- postgresql-simple
- postgresql-simple-migration
- resource-pool #Thread pools
- aeson #Json
- servant-server #Server connector
- katip #Loggin
- wai # http security - management
- wai-cors # http security - management
- warp #  http security - management
- lens # Optics lens
- hw-kafka-client

library:
  source-dirs: src

executables:
  gh-alerts-subscriptions-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gh-alerts-subscriptions-haskell

tests:
  gh-alerts-subscriptions-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gh-alerts-subscriptions-haskell
